version: "3.5"
networks:
  default:
    driver: bridge
services:
  application_service:
    container_name: testDocker
    restart: always
    build:
      context: ./testDocker
      dockerfile: Dockerfile
    ports:
      - "8079:8079"